# NUMPY: arrays

In [3]:
import numpy as np

In [4]:
lista = [1,2,3,4]

In [5]:
array = np.array(lista)

In [6]:
array

array([1, 2, 3, 4])

In [7]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
array2 = np.array(lista2)

In [10]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# NUMPY: arange,zeros,ones,linspace,eye

In [12]:
array = np.arange(5)

In [13]:
array

array([0, 1, 2, 3, 4])

In [14]:
np.arange(3,14)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [15]:
np.arange(3,14,4)

array([ 3,  7, 11])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# NUMPY: aleatorios, rand y randn y randint

In [24]:
np.random.rand(5)

array([0.04745673, 0.51560388, 0.02099509, 0.73594985, 0.08000456])

In [25]:
np.random.rand(1,4)

array([[0.7559742 , 0.73982378, 0.98183458, 0.24838986]])

In [26]:
np.random.randn(4)

array([ 0.5033136 ,  1.52387014, -1.58773406, -0.12011559])

In [27]:
np.random.randn(4,5)

array([[ 1.03026324,  1.27752604, -0.55702098,  0.36649836, -1.10374626],
       [-1.14339681,  0.73718587, -0.62664141,  1.63060322,  1.57359081],
       [-1.33740342, -0.26101216, -0.43922187,  0.29163462, -0.59010975],
       [ 0.60418995, -0.12667863,  1.65464156, -0.29680776,  0.87882518]])

In [29]:
np.random.randint(1,20)

6

In [30]:
np.random.randint(1,20,5)

array([11,  5, 10, 17,  1])

# NUMPY: reshape

In [31]:
array = np.random.randint(1,100,10)

In [32]:
array

array([46,  6, 77, 38, 32, 88, 35, 27, 13, 96])

In [38]:
matriz = array.reshape(5,2)

In [39]:
matriz

array([[46,  6],
       [77, 38],
       [32, 88],
       [35, 27],
       [13, 96]])

# NUMPY: max y min

In [40]:
array = np.random.randint(1,100,50)

In [41]:
array.max()

98

In [42]:
array.min()

7

In [43]:
array.argmax()

16

In [44]:
array.argmin()

41